- model_name: "anthropic/claude-sonnet-4-20250514"
  model_kwargs:
    temperature: 0.0
- model_name: "anthropic/claude-3-7-sonnet-20250219"
  model_kwargs:
    temperature: 0.0
- model_name: "@x-ai/grok-code-fast-1"
  model_class: portkey
  litellm_model_name_override: "xai/grok-code-fast-1"
- model_name: "@google/gemini-2.5-pro"
  model_class: portkey
- model_name: "@zhipu/glm-4.5"
  model_class: portkey
- model_name: "@openai/gpt-5"
  model_class: portkey
- model_name: "@openai/gpt-5-mini"
  model_class: portkey
- model_name: "@qwen/qwen-3-coder"
  model_class: portkey
- model_name: "@openai/o3"
  model_class: portkey
