game:
  name: BattleSnake
  rounds: 3
  args:
    width: 11
    height: 11
    browser: false
players:
- agent: mini
  name: p1
  config: configs/mini/battlesnake.yaml
  model: claude-sonnet-4-20250514
- agent: mini
  name: p2
  config: configs/mini/battlesnake.yaml
  model: claude-3-7-sonnet-20250219
