- model_name: "@anthropic/claude-sonnet-4-20250514"
  model_class: portkey
  model_kwargs:
    temperature: 0.2
    max_tokens: 4096
- model_name: "@anthropic/claude-sonnet-4-5-20250929"
  model_class: portkey
  model_kwargs:
    temperature: 0.2
    max_tokens: 4096
- model_name: "@x-ai/grok-code-fast-1"
  model_class: portkey
  litellm_model_name_override: "xai/grok-code-fast-1"
  model_kwargs:
    temperature: 0.2
- model_name: "@google/gemini-2.5-pro"
  model_class: portkey
  model_kwargs:
    temperature: 0.2
- model_name: "@openai/gpt-5"
  model_class: portkey
- model_name: "@openai/gpt-5-mini"
  model_class: portkey
- model_name: "dashscope/qwen3-coder-plus-2025-09-23"
  model_kwargs:
    temperature: 0.2
- model_name: "@openai/o3"
  model_class: portkey
