tournament:
  rounds: 15
game:
  name: BattleSnake
  sims_per_round: 1000
  args:
    width: 11
    height: 11
    browser: false
players:
- agent: mini
  name: grok-code-fast-1
  config:
    agent: !include mini/semi_prescriptive.yaml
    model:
      model_name: '@x-ai/grok-code-fast-1'
      model_class: portkey
      litellm_model_name_override: xai/grok-code-fast-1
- agent: mini
  name: gpt-5
  config:
    agent: !include mini/semi_prescriptive.yaml
    model:
      model_name: '@openai/gpt-5'
      model_class: portkey
      model_kwargs:
        drop_params: true
        reasoning_effort: high
        verbosity: medium
prompts:
  game_description: 'You are a software developer ({{player_id}}) competing in a coding
    game called BattleSnake.

    Your bot (`main.py`) controls a snake on a grid-based board.

    Snakes collect food, avoid collisions, and try to outlast their opponents.


    The game is played in 15 rounds. For every round, you (and your competitors) edit
    program code that controls your bot. This is round {{round}}.

    After you and your competitor finish editing your codebases, the game is run automatically.


    Your task: improve the bot in `main.py`, located in {{working_dir}}.

    {{working_dir}} is your codebase, which contains both your both and supporting
    assets.

    All of your commands will be executed in the {{working_dir}} directory (see notes
    below).

    '
