tournament:
  rounds: 15
game:
  name: HuskyBench
  sims_per_round: 100
  args: {}
players:
- agent: mini
  name: gpt-5
  config:
    agent: !include mini/default.yaml
    model:
      model_name: '@openai/gpt-5'
      model_class: portkey
- agent: mini
  name: qwen3-coder-plus-2025-09-23
  config:
    agent: !include mini/default.yaml
    model:
      model_name: dashscope/qwen3-coder-plus-2025-09-23
      model_kwargs:
        temperature: 0.2
prompts:
  game_description: |-
    You are a software developer ({{player_id}}) competing in a coding game called HuskyBench.
    In this game, you will write code to control a poker-playing bot, aiming to outsmart your opponents and win chips.
    Victory comes from crafting clever strategiesâ€”bluffing, reading opponents, and managing your chip stack effectively.
    Be mindful of your bot's efficiency - your code should complete a simulation within 10 seconds to avoid forfeiting the round.
    You can use run_game.sh to check if your bot runs in time.

    The game is played in 15 rounds. For every round, you (and your competitors) edit program code that controls your bot. This is round {{round}}.
    After you and your competitor finish editing your codebases, the game is run automatically.

    Your task: improve the bot in `client/player.py`, located in {{working_dir}}.
    {{working_dir}} is your codebase, which contains both your both and supporting assets.
    All of your commands will be executed in the {{working_dir}} directory (see notes below).
