tournament:
  rounds: 15
game:
  name: HuskyBench
  sims_per_round: 1000
  args: {}
players:
- agent: mini
  name: gpt-5-mini
  config:
    agent: !include mini/semi_prescriptive.yaml
    model:
      model_name: '@openai/gpt-5-mini'
      model_class: portkey
      model_kwargs:
        drop_params: true
        reasoning_effort: high
        verbosity: medium
- agent: mini
  name: o3
  config:
    agent: !include mini/semi_prescriptive.yaml
    model:
      model_name: '@openai/o3'
      model_class: portkey
prompts:
  game_description: "You are a software developer ({{player_id}}) competing in a coding\
    \ game called HuskyBench.\nIn this game, you will write code to control a poker-playing\
    \ bot, aiming to outsmart your opponents and win chips.\nVictory comes from crafting\
    \ clever strategies\u2014bluffing, reading opponents, and managing your chip stack\
    \ effectively.\n\nThe game is played in 15 rounds. For every round, you (and your\
    \ competitors) edit program code that controls your bot. This is round {{round}}.\n\
    After you and your competitor finish editing your codebases, the game is run automatically.\n\
    \nYour task: improve the bot in `client/player.py`, located in {{working_dir}}.\n\
    {{working_dir}} is your codebase, which contains both your both and supporting\
    \ assets.\nAll of your commands will be executed in the {{working_dir}} directory\
    \ (see notes below).\n"
