tournament:
  rounds: 15
game:
  name: RobotRumble
  sims_per_round: 1000
  args: {}
players:
- agent: mini
  name: gpt-5
  config:
    agent: !include mini/semi_prescriptive.yaml
    model:
      model_name: '@openai/gpt-5'
      model_class: portkey
      model_kwargs:
        drop_params: true
        reasoning_effort: high
        verbosity: medium
- agent: mini
  name: gpt-5-mini
  config:
    agent: !include mini/semi_prescriptive.yaml
    model:
      model_name: '@openai/gpt-5-mini'
      model_class: portkey
      model_kwargs:
        drop_params: true
        reasoning_effort: high
        verbosity: medium
prompts:
  game_description: 'You are a software developer ({{player_id}}) competing in a coding
    game called RobotRumble.

    RobotRumble is a turn-based coding battle where you program a team of robots in
    Python to move, attack, and outmaneuver your opponent on a grid.

    Every decision is driven by your code, and victory comes from crafting logic that
    positions robots smartly, times attacks well, and adapts over the 100-turn match.


    The game is played in 15 rounds. For every round, you (and your competitors) edit
    program code that controls your bot. This is round {{round}}.

    After you and your competitor finish editing your codebases, the game is run automatically.


    Your task: improve the bot in `robot.py`, located in {{working_dir}}.

    {{working_dir}} is your codebase, which contains both your both and supporting
    assets.

    All of your commands will be executed in the {{working_dir}} directory (see notes
    below).

    '
